const Trainees = [
  {
    timestamp: "11/20/2020 13:43:33",
    "Email Address": "Jewel@gmail.com",
    "First Name": "Jewel",
    "last Name": "Simon",
    company: "Fc Barcelona",
    "Profile Url": "https://jewel-7.github.io/Profile-Page/",
    "Pic Url":
      "https://raw.githubusercontent.com/raweng-academy/trainee-profile-page-collection/master/images/raw/RE-Jewel-Simon.jpeg?token=ARTS5CT5QZCLLU655B3IDWS7W55EW",
    "Alt description ": "Jewel",
  },
  {
    timestamp: "11/20/2020 13:52:24",
    "Email Address": "aditi07@gmail.com",
    "First Name": "Aditi",
    "last Name": "Pandit",
    Company: "Google",
    "Profile Url": "Dummy",
    "Pic Url": "Dummy",
    "Alt description ": "Aditi",
  },
  {
    timestamp: "11/20/2020 13:53:59",
    "Email Address": "shweta.bangera@serew.com",
    "First Name": "Shweta",
    "last Name": "Bangera",
    Company: "Serew",
    "Profile Url": "./pages/shweta/index.html",
    "Pic Url":
      "https://raw.githubusercontent.com/raweng-academy/trainee-profile-page-collection/master/images/raw/RE-Shweta-bangera.jpg?token=ARTS6UOABX4FJUIF7ZGDK5S7W55EO",
    "Alt description ": "Shweta image",
  },
  {
    timestamp: "11/20/2020 13:54:40",
    "Email Address": "tushar.mistry@mail.com",
    "First Name": "Tushar",
    "last Name": "Mistry",
    Company: "The Boys",
    "Profile Url": "https://mistycal98.github.io/profile/",
    "Pic Url":
      "https://raw.githubusercontent.com/raweng-academy/trainee-profile-page-collection/master/images/raw/RE-Tushar-Mistry.jpeg?token=ARTS45N2COZO3ZM2TADSS7S7W56TO",
    "Alt description ": "Tushar",
  },
  {
    timestamp: "11/20/2020 13:55:31",
    "Email Address": "venu.sripuram@treasure.com",
    "First Name": "Venu",
    "last Name": "Sripuram",
    Company: "Treasure",
    "Profile Url": "./pages/venu/index.html",
    "Pic Url": "venuimg.img",
    "Alt description ": "Venu image",
  },
  {
    timestamp: "11/20/2020 13:56:45",
    "Email Address": "ajin.varg@yahoo.com",
    "First Name": "Ajin",
    "last Name": "Varghese",
    Company: "AJ",
    "Profile Url": "https://ajin998.github.io/Aj-profile/Profile/",
    "Pic Url":
      "https://terrigen-cdn-dev.marvel.com/content/prod/1x/ironman_lob_mas_hlf_02_0.jpg",
    "Alt description ": "Ajin-Varghese",
  },
  {
    timestamp: "11/20/2020 13:57:04",
    "Email Address": "umeshmor643@gmail.com",
    "First Name": "Umesh",
    "last Name": "More",
    Company: "Random Company",
    "Profile Url": "https://umeshmore45.github.io/Portfolio-basic/index.html",
    "Pic Url":
      "https://raw.githubusercontent.com/raweng-academy/trainee-profile-page-collection/master/images/raw/RE-Umesh-More.jpeg?token=ARTS5PFICRXBV3YSXEETGRS7W56IS",
    "Alt description ": "umesh more",
  },
  {
    timestamp: "11/20/2020 13:58:10",
    "Email Address": "sumil@facebook.com",
    "First Name": "Sumil",
    "last Name": "Jain",
    Company: "Google",
    "Profile Url": "https://github.com/sumilraweng/blog",
    "Pic Url":
      "https://github.com/sumilraweng/blog/blob/main/assests/atricle-images/dev.jpg",
    "Alt description ":
      "I  am software engineer at raw engineering with having technical skills like html css react node and mongo with having some knowledge of oops and data structures & algo \n",
  },
  {
    timestamp: "11/20/2020 14:02:42",
    "Email Address": "name@company.com",
    "First Name": "Aditya",
    "last Name": "Shukla",
    Company: "RandomCompany",
    "Profile Url":
      "https://adityarawengg.github.io/My_Resume/improvedResume.html",
    "Pic Url":
      "https://raw.githubusercontent.com/raweng-academy/trainee-profile-page-collection/master/images/raw/RE-Aditya-Shukla.jpeg?token=ARTS5JVXNXD6XPHERCZDHQ27W57UC",
    "Alt description ": "Profile Image",
  },
  {
    timestamp: "11/20/2020 14:06:50",
    "Email Address": "snehalsutar@gmail.com",
    "First Name": "Snehal",
    "last Name": "Sutar",
    Company: "Aos company",
    "Profile Url": "https://github.com/Snehal/Profile-page",
    "Pic Url": "https://unsplash.com/photos/f5E1FR9vqIM",
    "Alt description ": "profile image",
  },
  {
    timestamp: "11/20/2020 14:09:02",
    "Email Address": "saurav.upadhyay@gmx.com",
    "First Name": "Saurav",
    "last Name": "Upadhyay",
    Company: "The Inside Media Pvt Ltd.",
    "Profile Url": "https://sauravraw.github.io/portfolio/",
    "Pic Url":
      "https://codersera.com/blog/wp-content/uploads/2019/07/BLOG-23-L-3.jpg",
    "Alt description ": "i don't have pic url :'( sorry",
  },
  {
    timestamp: "11/20/2020 14:09:05",
    "Email Address": "dishant123@gmail.com",
    "First Name": "Dishant",
    "last Name": "Patil",
    Company: "Stark Industries",
    "Profile Url": "https://dishant45.github.io/PROFILE/html/index.html",
    "Pic Url":
      "https://raw.githubusercontent.com/raweng-academy/trainee-profile-page-collection/master/images/raw/RE-Dishant-Patil.jpeg?token=ARTS7R6Q4NRTF4UKD5AFHL27W6ACW",
    "Alt description ": "Dishant ",
  },
  {
    timestamp: "11/20/2020 14:09:26",
    "Email Address": "ashwini.rathod@contentstack.com",
    "First Name": "Ashwini",
    "last Name": "Rathod",
    Company: "Contentstack",
    "Profile Url": "https://ashwini-rathod.github.io/Profile-page/",
    "Pic Url": "https://unsplash.com/photos/Hcfwew744z4",
    "Alt description ": "dummyPhoto",
  },
  {
    timestamp: "11/20/2020 14:20:22",
    "Email Address": "rishikesh.raut@raweng.com",
    "First Name": "Rishikesh",
    "last Name": "Raut",
    Company: "Raw Engineering",
    "Profile Url": "https://rishikesh46.github.io/Profilepage/",
    "Pic Url":
      "https://raw.githubusercontent.com/raweng-academy/trainee-profile-page-collection/master/images/raw/RE-rishekesh-raut.jpeg?token=ARTS5WCMEI7CAIJ5HPTV7427W6BSQ",
    "Alt description ": "Trainee",
  },
  {
    timestamp: "11/20/2020 14:21:12",
    "Email Address": "hardik.kundalia@mycompany.com",
    "First Name": "Hardik",
    "last Name": "Kundalia",
    Company: "My Company",
    "Profile Url": "https://khardik1698.github.io/ProfilePage/",
    "Pic Url":
      "https://raw.githubusercontent.com/raweng-academy/trainee-profile-page-collection/master/images/contenstack/CS-Hardik-Kundalia.jpeg?token=ARTSM5TW6N4LF7IJZDPXMUS7W6BQE",
    "Alt description ": "My Image",
  },
  {
    timestamp: "11/20/2020 14:23:07",
    "Email Address": "n.j26@gmail.com",
    "First Name": "Neeta",
    "last Name": "Jaiswal",
    Company: "XYZ",
    "Profile Url": "https://github.com/Neeta26/Resume",
    "Pic Url":
      "https://raw.githubusercontent.com/raweng-academy/trainee-profile-page-collection/master/images/raw/RE-Neeta-Jaiswal.jpeg?token",
    "Alt description ": "Neeta Jaiswal",
  },
  {
    timestamp: "11/20/2020 14:23:39",
    "Email Address": "rutuja@something.com",
    "First Name": "Rutuja",
    "last Name": "Patil",
    Company: "smthg pvt.ltd",
    "Profile Url": "https://rutuja9696.github.io/portfolioPg/portfolioPage/",
    "Pic Url":
      "https://github.com/Rutuja9696/portfolioPg/blob/master/portfolioPage/myLogo.png",
    "Alt description ": "This is a dummy data.",
  },
  {
    timestamp: "11/20/2020 14:29:31",
    "Email Address": "sagar.vartak@mail.com",
    "First Name": "Sagar",
    "last Name": "Vartak",
    Company: "C-Company",
    "Profile Url": "https://sagar-vartak.github.io/portfolio/index.html",
    "Pic Url":
      "https://images.unsplash.com/photo-1452800185063-6db5e12b8e2e?ixlib=rb-1.2.1&ixid=eyJhcHBfaWQiOjEyMDd9&auto=format&fit=crop&w=889&q=80",
    "Alt description ": "Dummy description",
  },
  {
    timestamp: "11/20/2020 14:31:13",
    "Email Address": "me@myself.com",
    "First Name": "Altaf",
    "last Name": "Shaikh",
    Company: "Pentester Academy",
    "Profile Url": "https://ialtafshaikh.github.io/",
    "Pic Url":
      "https://i.pinimg.com/736x/fd/a1/3b/fda13b9d6d88f25a9d968901d319216a.jpg",
    "Alt description ": "robot",
  },
  {
    timestamp: "11/20/2020 14:36:07",
    "Email Address": "adhijvartak@something.com",
    "First Name": "Adhij",
    "last Name": "Vartak",
    Company: "BuildUpPlay",
    "Profile Url":
      "https://vartakadhij-contentstack.github.io/Profile-Page/Profile-Page/",
    "Pic Url":
      "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRUZp6brBv-EElFK3GM6WUfEW7AE2L9VmGFzdlk81ZqhyhmS2Us0Z_8gJiA&s=10",
    "Alt description ": "Bruno Fernandes",
  },
  {
    timestamp: "11/20/2020 14:36:25",
    "Email Address": "abhaytank@xyz.com",
    "First Name": "Abhay",
    "last Name": "Tank",
    Company: "RE",
    "Profile Url": "https://abhay-tank.github.io/project-portfolio/",
    "Pic Url":
      "https://i.pinimg.com/originals/d8/14/31/d8143130dc24a02201fd55dc845b95a8.gif",
    "Alt description ": "abhay-avatar",
  },
  {
    timestamp: "11/20/2020 14:37:12",
    "Email Address": "lightyagami@gmail.com",
    "First Name": "Swati",
    "last Name": "Pandey",
    Company: "WonderWorld",
    "Profile Url": "https://github.com/SwaatiPandey/portfolio.git",
    "Pic Url":
      "https://icon-library.net/images/anonymous-female-icon/anonymous-female-icon-15.jpg",
    "Alt description ": "A female avatar",
  },
  {
    timestamp: "11/20/2020 14:38:26",
    "Email Address": "kritika0230.p@gmail.com",
    "First Name": "Kritika",
    "last Name": "Poojari",
    Company: "NEXT IT SOFTWARE SYSTEMS",
    "Profile Url": "NA",
    "Pic Url":
      "https://www.google.com/search?sxsrf=ALeKk021eoef2f1bn8ckq9awgWVTX1WVAA:1605863258539&q=dummy+image+&tbm=isch&chips=q:dummy+image,g_1:profile:bxB7KE4fDUY%3D&usg=AI4_-kSikhQF7XS8vlUD4SBihypJQt5LGA&sa=X&ved=2ahUKEwjZxdTo4pDtAhWvxjgGHUzgC4AQgIoDKAB6BAgPEAY&biw=1294&bih=637#imgrc=znsfer2Tuj3XrM",
    "Alt description ": "kritika-image",
  },
  {
    timestamp: "11/20/2020 14:45:15",
    "Email Address": "n.j26@gmail.com",
    "First Name": "Neeta",
    "last Name": "Jaiswal",
    Company: "XYZ",
    "Profile Url": "https://github.com/Neeta26/Resume",
    "Pic Url":
      "https://raw.githubusercontent.com/raweng-academy/trainee-profile-page-collection/master/images/raw/RE-Neeta-Jaiswal.jpeg?token",
    "Alt description ": "Neeta Jaiswal",
  },
  {
    timestamp: "11/20/2020 14:46:47",
    "Email Address": "n.j26@gmail.com",
    "First Name": "Neeta ",
    "last Name": "Jaiswal",
    Company: "XYZ",
    "Profile Url": "https://github.com/Neeta26/Resume",
    "Pic Url":
      "https://www.searchpng.com/wp-content/uploads/2019/02/Deafult-Profile-Pitcher.png",
    "Alt description ": "Neeta Jaiswal",
  },
  {
    timestamp: "11/20/2020 14:52:02",
    "Email Address": "aachal@gmail.com",
    "First Name": "Aachal",
    "last Name": "Vartak",
    Company: "RE",
    "Profile Url": "https://aachalv.github.io/Portfolio/",
    "Pic Url":
      "https://i.pinimg.com/originals/3a/74/5d/3a745d3dcba72feb73e44e399ec97bea.jpg",
    "Alt description ": "Aachal-Profile-Pic",
  },
];
